CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="C:/Users/Zach/Documents/CAPSTONE/external/bootloader/mcuboot/root-rsa-2048.pem"

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="MOTORSRV"
CONFIG_BT_GATT_CLIENT=n
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_GPIO=y

# console over UART
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_HWINFO=y # HARDWARE INFO

# logging system
CONFIG_LOG=y
# 0=off, 1=error, 2=warn, 3=info, 4=debug
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PRINTK=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_BT_SMP=y # SECURITY MANAGER PROTOCOL
CONFIG_BT_BONDABLE=y
CONFIG_BT_FIXED_PASSKEY=y

CONFIG_BT_SMP_SC_ONLY=y  # SECURE CONNECTIONS ONLY -> ONLY LEVEL 4 CONNECTIONS, IF A DEVICE DOESN'T SUPPORT THEN IT'S REJECTED

# FIRMWARE UPDATE - MCUMGR
CONFIG_MCUMGR=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_TRANSPORT_BT=y  # Bluetooth Transport for Updates

# FLASH
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_REBOOT=y

# BUFFERS TO INCREASE SPEED -> LARRGE BUFFERS
CONFIG_BT_L2CAP_TX_MTU=252
CONFIG_BT_BUF_ACL_RX_SIZE=256
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048