CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="C:/Users/Zach/Documents/CAPSTONE/external/bootloader/mcuboot/root-rsa-2048.pem"

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="MOTORSRV"
CONFIG_BT_GATT_CLIENT=n
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_GPIO=y

# console over UART
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_HWINFO=y # HARDWARE INFO

# logging system
CONFIG_LOG=y
# 0=off, 1=error, 2=warn, 3=info, 4=debug
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PRINTK=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_BT_SMP=y # SECURITY MANAGER PROTOCOL
CONFIG_BT_BONDABLE=y
CONFIG_BT_FIXED_PASSKEY=y

# CONFIG_BT_SMP_SC_ONLY=y  # SECURE CONNECTIONS ONLY -> ONLY LEVEL 4 CONNECTIONS, IF A DEVICE DOESN'T SUPPORT THEN IT'S REJECTED

# FIRMWARE UPDATE - MCUMGR
CONFIG_MCUMGR=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_TRANSPORT_BT=y  # Bluetooth Transport for Updates

# FLASH
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_REBOOT=y

# --- BLUETOOTH BUFFERS ---
# Decrease MTU slightly to be safe (Android default is often 247 for SMP)
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_TX_SIZE=251
# CRITICAL: Increase RX Buffer to handle MTU + Headers comfortably
# 256 was too small. 260+ is needed. 512 is safest.
CONFIG_BT_BUF_ACL_RX_SIZE=512

# Increase the count of buffers to prevent "Out of buffers" errors during fast updates
CONFIG_BT_BUF_ACL_RX_COUNT=6
CONFIG_BT_BUF_ACL_TX_COUNT=6

# --- MCUMGR SPECIFIC BUFFERS (MISSING) ---
# MCUMgr needs its own buffers to reassemble the image chunks
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=2475
CONFIG_MCUMGR_TRANSPORT_NETBUF_COUNT=4
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4096

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_BT_RX_STACK_SIZE=2048

CONFIG_ZCBOR=y
CONFIG_CRC=y